export const TRANSACTIONS_LIST_REQUEST = "TRANSACTIONS_LIST_REQUEST";
export const TRANSACTIONS_LIST_SUCCESS = "TRANSACTIONS_LIST_SUCCESS";
export const TRANSACTIONS_LIST_FAIL = "TRANSACTIONS_LIST_FAIL";