export const TRANSACTIONS_LIST_REQUEST = "TRANSACTIONS_LIST_REQUEST";
export const TRANSACTIONS_LIST_SUCCESS = "TRANSACTIONS_LIST_SUCCESS";
export const TRANSACTIONS_LIST_FAIL = "TRANSACTIONS_LIST_FAIL";

export const TRANSACTIONS_CREATE_SUCESS="TRANSACTIONS_CREATE_SUCESS";
export const TRANSACTION_CREATE_REQUEST="TRANSACTIONS_CREATE_REQUEST";
export const TRANSACTIONS_CREATE_FAIL="TRANSACTIONS_CREATE_FAIL";

export const TRANSACTIONS_DELETE_REQUEST = "TRANSACTIONS_DELETE_REQUEST";
export const TRANSACTIONS_DELETE_SUCCESS = "TRANSACTIONS_DELETE_SUCCESS";
export const TRANSACTIONS_DELETE_FAIL = "TRANSACTIONS_DELETE_FAIL";